### ISSUE TITLE
I Was Not Found Option Like This

### ISSUE THREAD

**Issue by 0xrasel** [YasserGersy/cazador_unr#3]
![image](https://user-images.githubusercontent.com/58187315/81401515-4c7f2180-9151-11ea-922f-1e95a1fbf183.png)

Domain And List Option is not available in my cazador..

here is my screenshot

![image](https://user-images.githubusercontent.com/58187315/81401692-abdd3180-9151-11ea-947b-49497d256608.png)

**Comment by YasserGersy** [comment]
*The screenshots contain different versions of the plugin . The old one allows you to list subdomains for a single domain , the updated version allows for multiple domains*.

**Regarding the domain** ,

 the Text box was replaced with a new input receiver  which allows you to set a fixed list or read from a file , just hit right click and select "Add entry" , then  type your value and hit enter , repeat the steps for multiple domains.


**Regarding  the list** which will be used  for brute-forcing , we replaced the text box with same above solution , the problem  ,by default  we  use a list which is stored in a file `App/Lists/subdomains_subdomains_prefix`  ,  the application before you submit this issue was expecting the user to set this list ,  we should have set it by default  ,  we  fixed it now.

https://github.com/YasserGersy/cazador_unr/commit/dcb0a5ea4a467bc31b41e8da9ef61cce0da373c3

Thanks for contributing

**Comment by YasserGersy** [comment]
Fixed.
